### ISSUE TITLE
What was wrong with the name "openui5-mobx-model"?

### ISSUE THREAD

**Issue by laszloKajan** [geekflyer/openui5-mobx-model#10]
@martinxxd What was wrong with the name "openui5-mobx-model"?
E.g. JSONModel, ODataModel, MobxModel.
"Binding" is used to mean data binding in the [documentation](https://openui5.hana.ondemand.com/#/api/sap.ui.model.Binding), not library binding. If anything, the name change introduces confusion.

**Comment by martwz** [comment]
`openui5-mobx-model` was already taken on NPM, and I don't have the rights to push to that repository.

**Comment by laszloKajan** [comment]
Ok, but that's also @geekflyer Christian Theilemann's. If he transferred ownership of this repo to you, surely he can arrange for the NPM package as well. I suggest instead of changing the name, straighten out the situation with Christian, since you are now the owner.

(By the way, I find discussing the issue here tedious, since it's only the the two of us.
You could email me directly lkajan@debian.org, or find me on Hangouts as laszlo.kajan@roche.com. I'm in time zone CET.)

**Comment by geekflyer** [comment]
don't have a strong name preference, but I indeed can easily transfer the npm module ownership to you @martinxxd , just let me know ur npm user.

**Comment by laszloKajan** [comment]
Excellent. If I may ask: can we please keep the name, and transfer module ownership?

**Comment by martwz** [comment]
@geekflyer thanks! My npm username is the same as on GitHub: [**martinxxd**](https://www.npmjs.com/~martinxxd). Will revert the repo name back to the old one afterwars.

**Comment by geekflyer** [comment]
@martinxxd sent you an invite.

**Comment by martwz** [comment]
Thanks @geekflyer, renamed to the old name and pushed a new release.

**Comment by laszloKajan** [comment]
Good news, thank you!
