### ISSUE TITLE
Contributors / Owners wanted!

### ISSUE THREAD

**Issue by geekflyer** [geekflyer/openui5-mobx-model#3]
Hi,

since I'm personally not working with SAPUI5 anymore, I'm looking for people to take over ownership of this repo.

Please let me know in this thread if you're interested.

Best Regards Christian

**Comment by geekflyer** [comment]
@laszloKajan

**Comment by laszloKajan** [comment]
Hello Christian @geekflyer !
Yes, I saw you left SAP. I'm sure they are sorry.
Indeed, I would like to make heavy use of your bindings.
I offer to take ownership of this repo.
Best regards,
Laszlo
