### ISSUE TITLE
How to use action/transactions with this wrapper ?

### ISSUE THREAD

**Issue by kyakubi** [geekflyer/openui5-mobx-model#7]
Is it already possible to use actions/transactions with this wrapper ?

https://mobx.js.org/refguide/action.html
https://mobx.js.org/refguide/transaction.html

**Comment by laszloKajan** [comment]
Hello kyakubi!
Of course. You use actions and transactions on the underlying MobX observable of the wrapper.
Best regards,
Laszlo
